#!/bin/sh --
set -e

usage() {
    echo "usage: $(basename "${0}") [target] [arch] [name]"
    exit 1
}

mklive() {
    ./mklive.sh -a "${arch}" \
        -T "${name} ${version} [$(date +%Y-%m-%d)]" \
        -k "de_CH-latin1" \
        -l "en_US.UTF-8" \
        -r "https://alpha.de.repo.voidlinux.org/current" \
        -r "https://alpha.de.repo.voidlinux.org/current/nonfree" \
        -r "/home/tm/code/contrib/void-packages/hostdir/binpkgs/voidvault" \
        -p "${pkgs}"
}

mkplatformfs() {
    ./mkplatformfs.sh "${arch}" \
        -p "${pkgs}"
}

rootfs() {
    ./mkrootfs.sh "${arch}"
}

if [ "${1}" = "-h" ] || [ "${1}" = "--help" ]; then
    usage
fi

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

target="${1:-live}"
arch="${2:-x86_64}"
name="${3:-Voidlinux}"
version="1.0.0"
pkgs="
base-devel
void-repo-nonfree
cryptsetup
btrfs-progs
git
curl
wget
inetutils
wifish
xtools
python3
go
rust
cargo
zsh
tmux
rakudo
voidvault
"

case "${target}" in
    live) mklive ;;
    platformfs) mkplatformfs ;;
    rootfs) rootfs ;;
    *) usage ;;
esac
